# Dockerfile-Frontend-Nginx-backend

# Usa una imagen base que incluya Java y Maven
FROM maven:3.8.4-openjdk-17 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo pom.xml para descargar las dependencias
COPY pom.xml .

# Descarga las dependencias
RUN mvn dependency:go-offline

# Copia los archivos del proyecto
COPY src src

# Compila la aplicación sin ejecutar las pruebas
RUN mvn package -Dmaven.test.skip=true

# Usa una imagen más ligera para la ejecución
FROM ubuntu:latest

# Actualiza el sistema e instala OpenJDK 17
RUN apt-get update && \
    apt-get install -y openjdk-17-jre

# Establece el directorio de trabajo
WORKDIR /app

# Copia solo los archivos necesarios desde la imagen de compilación
COPY target/ProyectoIIB-0.0.1-SNAPSHOT.jar app.jar

# Expone el puerto en el que la aplicación se ejecutará (ajusta según tus necesidades)
EXPOSE 3000

# Comando para ejecutar la aplicación al iniciar el contenedor
CMD ["java", "-jar", "app.jar"]
