version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db-procesos
      MYSQL_USER: lmpilamunga
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"